# Generated by Django 2.2.5 on 2019-09-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='rank_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
