# Generated by Django 2.2.5 on 2019-09-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_chapteroneweekone'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapteroneweekone',
            name='ChapterOneWeekOneQuestionThree',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chapteroneweekone',
            name='ChapterOneWeekOneQuestionTwo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chapteroneweekone',
            name='ChapterOneWeekTwoQuestionOne',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chapteroneweekone',
            name='ChapterOneWeekTwoQuestionThree',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chapteroneweekone',
            name='ChapterOneWeekTwoQuestionTwo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chapteroneweekone',
            name='ChapterThreeWeekOneQuestionOne',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chapteroneweekone',
            name='ChapterThreeWeekOneQuestionTwo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chapteroneweekone',
            name='ChapterThreeWeekTwoQuestionOne',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chapteroneweekone',
            name='ChapterThreeWeekTwoQuestionThree',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chapteroneweekone',
            name='ChapterThreeWeekTwoQuestionTwo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chapteroneweekone',
            name='ChapterThreoWeekOneQuestionThree',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chapteroneweekone',
            name='ChapterTwoWeekOneQuestionOne',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chapteroneweekone',
            name='ChapterTwoWeekOneQuestionThree',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chapteroneweekone',
            name='ChapterTwoWeekOneQuestionTwo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chapteroneweekone',
            name='ChapterTwoWeekTwoQuestionOne',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chapteroneweekone',
            name='ChapterTwoWeekTwoQuestionThree',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chapteroneweekone',
            name='ChapterTwoWeekTwoQuestionTwo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
