# Generated by Django 2.2.5 on 2019-09-08 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20190908_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapteroneweekone',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_ChOneWeekOne', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chapteroneweektwo',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_ChOneWeekTwo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chapterthreeweekone',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_ChThreeWeekOne', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chapterthreeweektwo',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_ChThreWeekTwo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chaptertwoweekone',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_ChTwoWeekOne', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chaptertwoweektwo',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_ChTwoWeekTwo', to=settings.AUTH_USER_MODEL),
        ),
    ]
