# Generated by Django 2.2.5 on 2019-09-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
