# Generated by Django 2.2.5 on 2019-09-08 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0003_userprofileinfo_chapteroneweekonequestionone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='ChapterOneWeekOneQuestionOne',
        ),
    ]
