# Generated by Django 2.2.5 on 2019-09-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0003_auto_20190903_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
