# Generated by Django 2.2.5 on 2019-09-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0004_remove_userprofileinfo_chapteroneweekonequestionone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='super_power',
            field=models.CharField(choices=[('Flash, the fastest', 'Flash, the fastest'), ('Hulk, the strongest', 'Hulk, the strongest'), ('Captain, the strategic', 'Captain, the strategic'), ('Spiderman, the stickiest', 'Spiderman, the stickiest')], default='Flash, the fastest', max_length=20),
        ),
    ]
