# Generated by Django 2.2.5 on 2019-09-03 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0005_auto_20190903_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
    ]
