# Generated by Django 2.2.5 on 2019-09-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0007_auto_20190903_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='age',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='kg',
            field=models.FloatField(null=True),
        ),
    ]
