# Generated by Django 2.2.5 on 2019-09-03 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0009_auto_20190903_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='age',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(5.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
