# Generated by Django 2.2.5 on 2019-09-04 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0014_auto_20190904_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(5.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(5.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='kg',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(5.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='super_power',
            field=models.CharField(choices=[('Fl', 'Flah the gratest'), ('Hl', 'Hulk all mighty'), ('Bt', 'Batman, the strategic'), ('Sp', 'Superman the call to advanture')], default='Fl', max_length=2),
        ),
    ]
