# Generated by Django 2.2.5 on 2019-09-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0018_auto_20190904_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
