# Generated by Django 2.2.5 on 2019-09-04 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0020_userprofileinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
    ]
