# Generated by Django 2.2.5 on 2019-09-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0027_auto_20190906_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='super_power',
            field=models.CharField(choices=[('Fl', 'Flah the gratest'), ('Hl', 'Hulk all mighty'), ('Bt', 'Batman, the strategic'), ('Sp', 'Superman the call to advanture')], default='Fl', max_length=2),
        ),
    ]
