# Generated by Django 2.2.5 on 2019-09-07 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0028_auto_20190906_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='use_extra', to=settings.AUTH_USER_MODEL),
        ),
    ]
